/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsReserveCacheRequest
 */
export interface CommonsReserveCacheRequest {
    /**
     * 
     * @type {string}
     * @memberof CommonsReserveCacheRequest
     */
    'cache_key': string;
    /**
     * ContentType contains the content type of the cache.  * This is not supported for GCS cache. When passed this will be ignored. *
     * @type {string}
     * @memberof CommonsReserveCacheRequest
     */
    'content_type'?: string;
    /**
     * NumberOfChunks contains the number of chunks the cache will be split into. Minimum value: 1. Maximum value: 10000.  * This is not supported for GCS cache. When passed this will be ignored. *
     * @type {number}
     * @memberof CommonsReserveCacheRequest
     */
    'number_of_chunks'?: number;
}

