/* tslint:disable */
/* eslint-disable */
/**
 * WarpCache
 * Caching server for WarpBuild
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: suppport@warpbuild.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsGetCacheStatsRequest
 */
export interface CommonsGetCacheStatsRequest {
    /**
     * 
     * @type {string}
     * @memberof CommonsGetCacheStatsRequest
     */
    'search_text'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsGetCacheStatsRequest
     */
    'stats_from_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsGetCacheStatsRequest
     */
    'stats_to_time'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CommonsGetCacheStatsRequest
     */
    'vcs_refs'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CommonsGetCacheStatsRequest
     */
    'vcs_repositories'?: Array<string>;
}

