/* tslint:disable */
/* eslint-disable */
/**
 * WarpCache
 * Caching server for WarpBuild
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: suppport@warpbuild.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsS3ReserveCacheResponse
 */
export interface CommonsS3ReserveCacheResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof CommonsS3ReserveCacheResponse
     */
    'pre_signed_urls'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CommonsS3ReserveCacheResponse
     */
    'upload_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsS3ReserveCacheResponse
     */
    'upload_key'?: string;
}

