/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsCacheEntry
 */
export interface CommonsCacheEntry {
    /**
     * 
     * @type {string}
     * @memberof CommonsCacheEntry
     */
    'cache_key'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsCacheEntry
     */
    'cache_version'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsCacheEntry
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsCacheEntry
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsCacheEntry
     */
    'organization_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsCacheEntry
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsCacheEntry
     */
    'vcs_organization_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsCacheEntry
     */
    'vcs_repository_name'?: string;
}

