/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsS3GetCacheResponse
 */
export interface CommonsS3GetCacheResponse {
    /**
     * 
     * @type {string}
     * @memberof CommonsS3GetCacheResponse
     */
    'cache_key'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsS3GetCacheResponse
     */
    'cache_version'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsS3GetCacheResponse
     */
    'pre_signed_url'?: string;
}

