/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TypesCompletedPart } from './types-completed-part';

/**
 * 
 * @export
 * @interface CommonsCommitCacheRequest
 */
export interface CommonsCommitCacheRequest {
    /**
     * 
     * @type {string}
     * @memberof CommonsCommitCacheRequest
     */
    'cache_key': string;
    /**
     * 
     * @type {string}
     * @memberof CommonsCommitCacheRequest
     */
    'cache_version': string;
    /**
     * 
     * @type {string}
     * @memberof CommonsCommitCacheRequest
     */
    'os': string;
    /**
     * 
     * @type {Array<TypesCompletedPart>}
     * @memberof CommonsCommitCacheRequest
     */
    'parts': Array<TypesCompletedPart>;
    /**
     * UploadID  * This is not supported for GCS cache. When passed this will be ignored. *
     * @type {string}
     * @memberof CommonsCommitCacheRequest
     */
    'upload_id'?: string;
    /**
     * UploadKey  * This is not supported for GCS cache. When passed this will be ignored. *
     * @type {string}
     * @memberof CommonsCommitCacheRequest
     */
    'upload_key'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsCommitCacheRequest
     */
    'vcs_type': string;
}

