/* tslint:disable */
/* eslint-disable */
/**
 * WarpCache
 * Caching server for WarpBuild
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: suppport@warpbuild.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CommonsCacheEntry } from './commons-cache-entry';
// May contain unused imports in some cases
// @ts-ignore
import { CommonsGCSGetCacheReponse } from './commons-gcsget-cache-reponse';
// May contain unused imports in some cases
// @ts-ignore
import { CommonsS3GetCacheResponse } from './commons-s3-get-cache-response';

/**
 * 
 * @export
 * @interface CommonsGetCacheResponse
 */
export interface CommonsGetCacheResponse {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CommonsGetCacheResponse
     */
    'annotations'?: { [key: string]: string; };
    /**
     * 
     * @type {CommonsCacheEntry}
     * @memberof CommonsGetCacheResponse
     */
    'cache_entry'?: CommonsCacheEntry;
    /**
     * 
     * @type {CommonsGCSGetCacheReponse}
     * @memberof CommonsGetCacheResponse
     */
    'gcs'?: CommonsGCSGetCacheReponse;
    /**
     * 
     * @type {string}
     * @memberof CommonsGetCacheResponse
     */
    'provider'?: string;
    /**
     * 
     * @type {CommonsS3GetCacheResponse}
     * @memberof CommonsGetCacheResponse
     */
    's3'?: CommonsS3GetCacheResponse;
}

