/* tslint:disable */
/* eslint-disable */
/**
 * WarpCache
 * Caching server for WarpBuild
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: suppport@warpbuild.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsListCacheReposResponse
 */
export interface CommonsListCacheReposResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof CommonsListCacheReposResponse
     */
    'vcs_repositories'?: Array<string>;
}

