/* tslint:disable */
/* eslint-disable */
/**
 * WarpCache
 * Caching server for WarpBuild
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: suppport@warpbuild.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsCacheEntryMetadata
 */
export interface CommonsCacheEntryMetadata {
    /**
     * 
     * @type {string}
     * @memberof CommonsCacheEntryMetadata
     */
    'cloud_connection_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsCacheEntryMetadata
     */
    'runner_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsCacheEntryMetadata
     */
    'stack_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsCacheEntryMetadata
     */
    'stack_name'?: string;
}

