/* tslint:disable */
/* eslint-disable */
/**
 * WarpCache
 * Caching server for WarpBuild
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: suppport@warpbuild.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsListCacheRequest
 */
export interface CommonsListCacheRequest {
    /**
     * 
     * @type {number}
     * @memberof CommonsListCacheRequest
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof CommonsListCacheRequest
     */
    'per_page'?: number;
    /**
     * 
     * @type {string}
     * @memberof CommonsListCacheRequest
     */
    'search_text'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsListCacheRequest
     */
    'sort_by_field'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsListCacheRequest
     */
    'sort_order'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CommonsListCacheRequest
     */
    'vcs_refs'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CommonsListCacheRequest
     */
    'vcs_repositories'?: Array<string>;
}

