/* tslint:disable */
/* eslint-disable */
/**
 * WarpCache
 * Caching server for WarpBuild
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: suppport@warpbuild.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsDeleteCacheRequest
 */
export interface CommonsDeleteCacheRequest {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CommonsDeleteCacheRequest
     */
    'annotations'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof CommonsDeleteCacheRequest
     */
    'cache_key': string;
    /**
     * 
     * @type {string}
     * @memberof CommonsDeleteCacheRequest
     */
    'cache_version': string;
    /**
     * VCSRef is the ref of the repository in vcs for which cache is being used. This can be a branch, git tag, or pull request ref.
     * @type {string}
     * @memberof CommonsDeleteCacheRequest
     */
    'vcs_ref'?: string;
    /**
     * VCSRepository is the repository name in vcs. It can be of the format <organization>/<repository> or <repository>. While saving the entry, <organization>/ will be trimmed if passed.
     * @type {string}
     * @memberof CommonsDeleteCacheRequest
     */
    'vcs_repository'?: string;
}

