/* tslint:disable */
/* eslint-disable */
/**
 * WarpCache
 * Caching server for WarpBuild
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: suppport@warpbuild.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsOperation
 */
export interface CommonsOperation {
    /**
     * 
     * @type {string}
     * @memberof CommonsOperation
     */
    'cache_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsOperation
     */
    'created-at'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsOperation
     */
    'id'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CommonsOperation
     */
    'meta'?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof CommonsOperation
     */
    'operation_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsOperation
     */
    'organization_id'?: string;
    /**
     * 
     * @type {number}
     * @memberof CommonsOperation
     */
    'size'?: number;
    /**
     * 
     * @type {string}
     * @memberof CommonsOperation
     */
    'time'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsOperation
     */
    'updated_at'?: string;
}

