/* tslint:disable */
/* eslint-disable */
/**
 * WarpCache
 * Caching server for WarpBuild
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: suppport@warpbuild.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsDaywiseCost
 */
export interface CommonsDaywiseCost {
    /**
     * 
     * @type {number}
     * @memberof CommonsDaywiseCost
     */
    'amount': number;
    /**
     * 
     * @type {number}
     * @memberof CommonsDaywiseCost
     */
    'cumulative_amount': number;
    /**
     * 
     * @type {string}
     * @memberof CommonsDaywiseCost
     */
    'date': string;
}

