/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CommonsGCSGetCacheReponse } from './commons-gcsget-cache-reponse';
// May contain unused imports in some cases
// @ts-ignore
import { CommonsS3GetCacheResponse } from './commons-s3-get-cache-response';

/**
 * 
 * @export
 * @interface CommonsGetCacheResponse
 */
export interface CommonsGetCacheResponse {
    /**
     * 
     * @type {CommonsGCSGetCacheReponse}
     * @memberof CommonsGetCacheResponse
     */
    'gcs'?: CommonsGCSGetCacheReponse;
    /**
     * 
     * @type {string}
     * @memberof CommonsGetCacheResponse
     */
    'provider'?: string;
    /**
     * 
     * @type {CommonsS3GetCacheResponse}
     * @memberof CommonsGetCacheResponse
     */
    's3'?: CommonsS3GetCacheResponse;
}

