/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CommonsShortLivedToken } from './commons-short-lived-token';

/**
 * 
 * @export
 * @interface CommonsGCSGetCacheReponse
 */
export interface CommonsGCSGetCacheReponse {
    /**
     * 
     * @type {string}
     * @memberof CommonsGCSGetCacheReponse
     */
    'bucket_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsGCSGetCacheReponse
     */
    'cache_key'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsGCSGetCacheReponse
     */
    'cache_version'?: string;
    /**
     * Method contains the auth method to be used to connect to the GCP storage backend
     * @type {string}
     * @memberof CommonsGCSGetCacheReponse
     */
    'method'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsGCSGetCacheReponse
     */
    'project_id'?: string;
    /**
     * 
     * @type {CommonsShortLivedToken}
     * @memberof CommonsGCSGetCacheReponse
     */
    'short_lived_token'?: CommonsShortLivedToken;
}

