/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CommonsCacheEntry } from './commons-cache-entry';
// May contain unused imports in some cases
// @ts-ignore
import { CommonsGCSDeleteCacheResponse } from './commons-gcsdelete-cache-response';
// May contain unused imports in some cases
// @ts-ignore
import { CommonsS3DeleteCacheResponse } from './commons-s3-delete-cache-response';

/**
 * 
 * @export
 * @interface CommonsDeleteCacheResponse
 */
export interface CommonsDeleteCacheResponse {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CommonsDeleteCacheResponse
     */
    'annotations'?: { [key: string]: string; };
    /**
     * 
     * @type {CommonsCacheEntry}
     * @memberof CommonsDeleteCacheResponse
     */
    'cache_entry'?: CommonsCacheEntry;
    /**
     * 
     * @type {CommonsGCSDeleteCacheResponse}
     * @memberof CommonsDeleteCacheResponse
     */
    'gcs'?: CommonsGCSDeleteCacheResponse;
    /**
     * 
     * @type {string}
     * @memberof CommonsDeleteCacheResponse
     */
    'provider'?: string;
    /**
     * 
     * @type {CommonsS3DeleteCacheResponse}
     * @memberof CommonsDeleteCacheResponse
     */
    's3'?: CommonsS3DeleteCacheResponse;
}

