/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsGetCacheRequest
 */
export interface CommonsGetCacheRequest {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CommonsGetCacheRequest
     */
    'annotations'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof CommonsGetCacheRequest
     */
    'cache_key': string;
    /**
     * 
     * @type {string}
     * @memberof CommonsGetCacheRequest
     */
    'cache_version': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CommonsGetCacheRequest
     */
    'restore_keys'?: Array<string>;
    /**
     * VCSRef is the ref of the repository in vcs for which cache is being used. This can be a branch, git tag, or pull request ref.
     * @type {string}
     * @memberof CommonsGetCacheRequest
     */
    'vcs_ref'?: string;
    /**
     * VCSRepository is the repository name in vcs. It can be of the format <organization>/<repository> or <repository>. While saving the entry, <organization>/ will be trimmed if passed.
     * @type {string}
     * @memberof CommonsGetCacheRequest
     */
    'vcs_repository'?: string;
}

