/* tslint:disable */
/* eslint-disable */
/**
 * WarpCache
 * Caching server for WarpBuild
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: suppport@warpbuild.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TypesCompletedPart } from './types-completed-part';

/**
 * 
 * @export
 * @interface CommonsCommitCacheRequest
 */
export interface CommonsCommitCacheRequest {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CommonsCommitCacheRequest
     */
    'annotations'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof CommonsCommitCacheRequest
     */
    'cache_key': string;
    /**
     * 
     * @type {string}
     * @memberof CommonsCommitCacheRequest
     */
    'cache_version': string;
    /**
     * 
     * @type {Array<TypesCompletedPart>}
     * @memberof CommonsCommitCacheRequest
     */
    'parts': Array<TypesCompletedPart>;
    /**
     * 
     * @type {string}
     * @memberof CommonsCommitCacheRequest
     */
    'provider'?: string;
    /**
     * UploadID  * This is not supported for GCS cache. When passed this will be ignored. *
     * @type {string}
     * @memberof CommonsCommitCacheRequest
     */
    'upload_id'?: string;
    /**
     * UploadKey  * This is not supported for GCS cache. When passed this will be ignored. *
     * @type {string}
     * @memberof CommonsCommitCacheRequest
     */
    'upload_key'?: string;
    /**
     * VCSRef is the ref of the repository in vcs for which cache is being used. This can be a branch, git tag, or pull request ref.
     * @type {string}
     * @memberof CommonsCommitCacheRequest
     */
    'vcs_ref'?: string;
    /**
     * VCSRepository is the repository name in vcs. It can be of the format <organization>/<repository> or <repository>. While saving the entry, <organization>/ will be trimmed if passed.
     * @type {string}
     * @memberof CommonsCommitCacheRequest
     */
    'vcs_repository'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsCommitCacheRequest
     */
    'vcs_type': string;
}

