/* tslint:disable */
/* eslint-disable */
/**
 * WarpCache
 * Caching server for WarpBuild
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: suppport@warpbuild.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsDailyOperationsBreakdown
 */
export interface CommonsDailyOperationsBreakdown {
    /**
     * 
     * @type {number}
     * @memberof CommonsDailyOperationsBreakdown
     */
    'count'?: number;
    /**
     * 
     * @type {number}
     * @memberof CommonsDailyOperationsBreakdown
     */
    'cumulative_count'?: number;
    /**
     * 
     * @type {number}
     * @memberof CommonsDailyOperationsBreakdown
     */
    'cumulative_size'?: number;
    /**
     * 
     * @type {string}
     * @memberof CommonsDailyOperationsBreakdown
     */
    'date'?: string;
    /**
     * 
     * @type {number}
     * @memberof CommonsDailyOperationsBreakdown
     */
    'size'?: number;
}

