/* tslint:disable */
/* eslint-disable */
/**
 * WarpCache
 * Caching server for WarpBuild
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: suppport@warpbuild.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CommonsDailyOperationsBreakdown } from './commons-daily-operations-breakdown';

/**
 * 
 * @export
 * @interface CommonsGetCacheStatsResponse
 */
export interface CommonsGetCacheStatsResponse {
    /**
     * 
     * @type {number}
     * @memberof CommonsGetCacheStatsResponse
     */
    'average_cache_operations'?: number;
    /**
     * 
     * @type {number}
     * @memberof CommonsGetCacheStatsResponse
     */
    'average_cache_usage'?: number;
    /**
     * 
     * @type {number}
     * @memberof CommonsGetCacheStatsResponse
     */
    'current_total_cache_size'?: number;
    /**
     * 
     * @type {Array<CommonsDailyOperationsBreakdown>}
     * @memberof CommonsGetCacheStatsResponse
     */
    'daily_breakdown'?: Array<CommonsDailyOperationsBreakdown>;
    /**
     * 
     * @type {number}
     * @memberof CommonsGetCacheStatsResponse
     */
    'total_cache_operations'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof CommonsGetCacheStatsResponse
     */
    'unique_vcs_refs'?: Array<string>;
}

