/* tslint:disable */
/* eslint-disable */
/**
 * WarpCache
 * Caching server for WarpBuild
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: suppport@warpbuild.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsS3CommitCacheResponse
 */
export interface CommonsS3CommitCacheResponse {
    /**
     * 
     * @type {string}
     * @memberof CommonsS3CommitCacheResponse
     */
    'cache_key': string;
    /**
     * 
     * @type {string}
     * @memberof CommonsS3CommitCacheResponse
     */
    'cache_version': string;
}

