/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CommonsGCSCommitCacheResponse } from './commons-gcscommit-cache-response';
// May contain unused imports in some cases
// @ts-ignore
import { CommonsS3CommitCacheResponse } from './commons-s3-commit-cache-response';

/**
 * 
 * @export
 * @interface CommonsCommitCacheResponse
 */
export interface CommonsCommitCacheResponse {
    /**
     * 
     * @type {CommonsGCSCommitCacheResponse}
     * @memberof CommonsCommitCacheResponse
     */
    'gcs'?: CommonsGCSCommitCacheResponse;
    /**
     * 
     * @type {string}
     * @memberof CommonsCommitCacheResponse
     */
    'provider'?: string;
    /**
     * 
     * @type {CommonsS3CommitCacheResponse}
     * @memberof CommonsCommitCacheResponse
     */
    's3'?: CommonsS3CommitCacheResponse;
}

