/* tslint:disable */
/* eslint-disable */
/**
 * WarpCache
 * Caching server for WarpBuild
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: suppport@warpbuild.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsS3GetCacheResponse
 */
export interface CommonsS3GetCacheResponse {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CommonsS3GetCacheResponse
     */
    'annotations'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof CommonsS3GetCacheResponse
     */
    'cache_key'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsS3GetCacheResponse
     */
    'cache_version'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsS3GetCacheResponse
     */
    'pre_signed_url'?: string;
}

