/* tslint:disable */
/* eslint-disable */
/**
 * WarpCache
 * Caching server for WarpBuild
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: suppport@warpbuild.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CommonsCacheEntry } from './commons-cache-entry';
// May contain unused imports in some cases
// @ts-ignore
import { CommonsGCSCommitCacheResponse } from './commons-gcscommit-cache-response';
// May contain unused imports in some cases
// @ts-ignore
import { CommonsS3CommitCacheResponse } from './commons-s3-commit-cache-response';

/**
 * 
 * @export
 * @interface CommonsCommitCacheResponse
 */
export interface CommonsCommitCacheResponse {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CommonsCommitCacheResponse
     */
    'annotations'?: { [key: string]: string; };
    /**
     * 
     * @type {CommonsCacheEntry}
     * @memberof CommonsCommitCacheResponse
     */
    'cache_entry'?: CommonsCacheEntry;
    /**
     * 
     * @type {CommonsGCSCommitCacheResponse}
     * @memberof CommonsCommitCacheResponse
     */
    'gcs'?: CommonsGCSCommitCacheResponse;
    /**
     * 
     * @type {string}
     * @memberof CommonsCommitCacheResponse
     */
    'provider'?: string;
    /**
     * 
     * @type {CommonsS3CommitCacheResponse}
     * @memberof CommonsCommitCacheResponse
     */
    's3'?: CommonsS3CommitCacheResponse;
    /**
     * VCSRepository is the repository name in vcs. It can be of the format <organization>/<repository> or <repository>. While saving the entry, <organization>/ will be trimmed if passed.
     * @type {string}
     * @memberof CommonsCommitCacheResponse
     */
    'vcs_repository'?: string;
}

