/* tslint:disable */
/* eslint-disable */
/**
 * WarpCache
 * Caching server for WarpBuild
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: suppport@warpbuild.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonsAzureBlobGetCacheResponse
 */
export interface CommonsAzureBlobGetCacheResponse {
    /**
     * 
     * @type {string}
     * @memberof CommonsAzureBlobGetCacheResponse
     */
    'bucket_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsAzureBlobGetCacheResponse
     */
    'cache_key'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsAzureBlobGetCacheResponse
     */
    'cache_version'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonsAzureBlobGetCacheResponse
     */
    'pre_signed_url'?: string;
}

