/* tslint:disable */
/* eslint-disable */
/**
 * WarpCache
 * Caching server for WarpBuild
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: suppport@warpbuild.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WarpBuildAPIError
 */
export interface WarpBuildAPIError {
    /**
     * 
     * @type {string}
     * @memberof WarpBuildAPIError
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof WarpBuildAPIError
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof WarpBuildAPIError
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof WarpBuildAPIError
     */
    'sub_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof WarpBuildAPIError
     */
    'sub_message'?: string;
}

