#!/usr/bin/env bash

set -eo pipefail

name=$1

if [[ -z "$name" ]]; then
  >&2 echo "Usage: npm run new-package [name]"
  exit 1
fi

npx lerna create @actions/$name
cp packages/core/tsconfig.json packages/$name/tsconfig.json