# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: release

on:
  push:
    branches:
      - main
    paths:
      - '.changeset/**'
  workflow_run:
    workflows:
      - unit-tests
    branches:
      - main
    types:
      - completed

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    if: ${{ github.repository == 'unlike-ltd/github-actions-toolkit' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup Node.js Pnpm & install dependencies
        uses: unlike-ltd/github-actions/setup-pnpm@main
        with:
          node-version: 16.x

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1.4.4
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
