name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions: write-all

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: fopina/upstream-to-pr@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          upstream-repository: https://github.com/actions/toolkit.git